--- 
name: Ext JS 3.1.0 Source
platform_id: all
platform_version: all
distribution_file_uuid_string: openlogic-extjs-3.1.0-all-src-1
platform_vendor: all
description: Ext JS 3.1.0 Source
platform_arch: all
distribution_file_uuid: 05c38a9708536b7aa8cbc2cd556e2e237f7a02e1a9dc26dfbe5679241878d3f7
distribution_version: 1
distribution_flavor: ""
distribution_raw_file: 3.1.0/ext-3.1.0.zip
notify: "yes"
package_version: 3.1.0
package_id: extjs
release_date: "2011-06-30"
distribution_notes: ""
distribution_type: src
